#!/bin/sh

# used to copy all pdf files into a destination folder, for example a Google Drive shared folder.

# xcopy /s "D:\boirl\GitHub\newsletters-pjb-canada\website\canada\pdf" "D:\boirl\Google Drive\Canada\Newsletters"
cp -a "/d/boirl/GitHub/newsletters-pjb-canada/website/canada/pdf/." "/d/boirl/Google Drive/Canada/Newsletters/"